version: '3.8'

services:
    nginx:
        build:
            context: ./docker/nginx
        ports:
            - "${NGINX_PORT:-80}:80"
        volumes:
            - ./:/var/www/html
        depends_on:
            - php
        networks:
            - app-network

    php:
        build:
            context: ./docker/php
        volumes:
            - ./:/var/www/html
        networks:
            - app-network

    mariadb:
        image: mariadb:10.6
        ports:
            - "${DB_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - ~/.docker-data/data/mariadb:/var/lib/mysql
        networks:
            - app-network

    redis:
        image: redis:alpine
        ports:
            - "${REDIS_PORT:-6379}:6379"
        volumes:
            - ~/.docker-data/data/redis:/data
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "${PMA_PORT:-8080}:80"
        environment:
            PMA_HOST: mariadb
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
        networks:
            - app-network
        depends_on:
            - mariadb

    mailpit:
        image: axllent/mailpit
        ports:
            - "${MAIL_PORT:-1025}:1025"
            - "${MAIL_DASHBOARD_PORT:-8025}:8025"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mariadb-data:
    redis-data:
